dist: bionic
language: cpp
compiler: gcc

matrix:
    - addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test    
            packages:
                - cmake
                - libfmt-dev
                - libprotobuf-dev
                - protobuf-compiler
                - libgles2-mesa-dev
                - libegl1-mesa-dev

install:
    - cmake --version

script:
    - scripts/test.sh
