dist: bionic
language: cpp
compiler: gcc

matrix:
    - addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test    
            packages:
                - cmake
                - libfmt-dev
                - libprotobuf-dev
                - protobuf-compiler

install:
    - cmake --version

script:
    - scripts/test.sh
