dist: bionic
language: cpp
compiler: gcc

matrix:
    - addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test    
            packages:
                - cmake
                - libfmt-dev # fmt-packaged
                - libprotobuf-dev # protobuf-packaged
                - protobuf-compiler # protobuf-packaged
                - libgles2-mesa-dev # raylib, glfw
                - libegl1-mesa-dev # raylib, glfw
                - libxrandr-dev # raylib, glfw
                - libxinerama-dev # raylib, glfw
                - libxcursor-dev # raylib, glfw
                - libxi-dev # raylib, glfw
install:
    - cmake --version

script:
    - scripts/test.sh
