dist: bionic
language: cpp
compiler: gcc

matrix:
    - addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test    
            packages:
                - cmake
                - libfmt-dev

install:
    - cmake --version

script:
    - cd scripts
    - ./test.sh
