dist: bionic
language: cpp
compiler: gcc

matrix:
    - addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test    
            packages:
                - cmake
                - libfmt-dev # fmt-packaged
                - libprotobuf-dev # protobuf-packaged
                - protobuf-compiler # protobuf-packaged
install:
    - cmake --version

script:
    - scripts/test.sh
