dist: bionic
language: cpp
compiler: gcc

matrix:
    - addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test    
                - george-edison55-precise-backports
            packages:
                - cmake-data
                - cmake
                - libdfmt-dev

script:
    - cd scripts
    - ./test.sh
