function (fetch_package_with_database package) 
    include(FetchContent)
    FetchContent_Declare(
        cunta_database
        GIT_REPOSITORY https://github.com/shrumo/cunta.git
    )
    FetchContent_GetProperties(cunta_database)
    if(NOT cunta_database_POPULATED)
        message("Fetching cunta_database")
        FetchContent_Populate(cunta_database)
        include(${cunta_database_SOURCE_DIR}/cunta_database.cmake)
    endif()
    find_git_package(${ARGV})
endfunction()
    

function (find_or_fetch_package package)
    set(required 0)
    if("REQUIRED" IN_LIST ARGV)
        set(required 1)
        list(REMOVE_ITEM ARGV "REQUIRED")
    endif()
    
    find_package(${ARGV})
    if (NOT ${${package}_FOUND}) 
        fetch_package_with_database(${ARGV})
    endif()
    if (NOT ${${package}_FOUND} AND NOT ${${package}_GIT_FOUND})
        set(message_level "STATUS")
        if(${required})
            set(message_level "FATAL_ERROR")
        endif()
        if(NOT "QUIET" IN_LIST ARGV)
            message(${message_level} ${package} " not found.")
        endif()
    endif()
endfunction()
